apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: miacr.azurecr.io/demo-app:v2  # <-- Cambia esto por tu imagen real
        ports:
        - containerPort: 80
